apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: mce-capi-webhook-config-service-cert
  labels:
    app: mce-capi-webhook-config
  name: mce-capi-webhook-config-service
  namespace: '{{ default "capi-system" .Values.global.namespace }}'
spec:
  ports:
  - port: 9443
    targetPort: 9443
  selector:
    app: mce-capi-webhook-config
